modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "goblinmines_minecart_tweaks"
version = "${version}"
displayName = "Goblinmine`s Minecart Tweaks"
authors = "Goblinmine"
description = '''
This mod is for everyone who want minecarts to be a viable method of travel again!
It buffs the speed of the powered rail and adds the copper rail as as a cheaper powered rail option with vanilla speed
'''
#logoFile = ""

[[dependencies.goblinmines_minecart_tweaks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.goblinmines_minecart_tweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.goblinmines_minecart_tweaks]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
